import { StyleSheet } from 'react-native';

/** Gallery Light — warm stone ground, photo-forward, ink accents. */
export const colors = {
  bg: '#e8e4dc',
  card: '#f7f5f1',
  text: '#1a1814',
  textMuted: '#6b6560',
  primary: '#2c2824',
  primaryPressed: '#1a1814',
  danger: '#9b3b32',
  border: '#d4cfc6',
  overdue: '#9b3b32',
  dueSoon: '#a65f2a',
  accent: '#5c6b52',
  upcomingMonthBg: '#efe6d4',
  upcomingWeekBg: '#e4d4b8',
  upcomingOverdueBg: '#f0e4e2',
  historyCardBg: '#efeae3',
  upcomingCardBg: '#e9e2d6',
  photoPlaceholder: '#d4cfc6',
  hairline: '#cfc8bc',
  /** Last-service accents on Room asset list rows. */
  lastService: '#2f6b3a',
  /** All-caps section titles (Service schedule, Assets, Rooms, etc.). */
  sectionTitle: '#1f5fbf',
};

export const sharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  screenHeader: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    backgroundColor: colors.bg,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  backBtn: {
    padding: 4,
  },
  backBtnText: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  title: {
    flex: 1,
    fontSize: 28,
    fontWeight: '600',
    color: colors.text,
    letterSpacing: -0.4,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textMuted,
    marginBottom: 12,
    lineHeight: 20,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.hairline,
    padding: 16,
    marginBottom: 12,
  },
  cardPressed: {
    opacity: 0.88,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.text,
    letterSpacing: -0.2,
  },
  cardMeta: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
    lineHeight: 18,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.sectionTitle,
    marginTop: 16,
    marginBottom: 12,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  /** Quiet panel for distinct screen subsections (e.g. Asset service areas). */
  sectionFrame: {
    backgroundColor: colors.card,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.hairline,
    padding: 16,
    marginBottom: 16,
  },
  /** Catalog-style detail block — minimal chrome for editable sections. */
  catalogSection: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.hairline,
    paddingVertical: 18,
    paddingHorizontal: 0,
    marginBottom: 0,
  },
  textLink: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
    letterSpacing: 0.3,
  },
  emptyText: {
    fontSize: 15,
    color: colors.textMuted,
    textAlign: 'center',
    paddingVertical: 28,
    lineHeight: 22,
  },
  primaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: 4,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginTop: 12,
  },
  primaryBtnPressed: {
    backgroundColor: colors.primaryPressed,
  },
  primaryBtnText: {
    color: '#f7f5f1',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  secondaryBtn: {
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  secondaryBtnText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  dangerBtn: {
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.danger,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  dangerBtnText: {
    color: colors.danger,
    fontSize: 15,
    fontWeight: '500',
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: 12,
    letterSpacing: 0.6,
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 4,
    backgroundColor: colors.card,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 16,
    color: colors.text,
  },
  inputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  galleryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  galleryTile: {
    width: '48%',
    marginBottom: 16,
  },
  galleryImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 2,
    backgroundColor: colors.photoPlaceholder,
  },
  galleryCaption: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.text,
    marginTop: 8,
    letterSpacing: -0.1,
  },
  galleryMeta: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
});
